name: "AniList"
guid: "1bd22884-44be-40f3-ad95-fc4a7834ba2c"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 8
targetAbi: "10.8.12.0"
framework: "net6.0"
owner: "jellyfin"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  - Tweaked AnilistSearchHelper.PreprocessTitle() to handle more search failures
  - update dotnet monorepo to v8
